/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({ objects, playing }) {
  const {huizen, bomen, boten, vliegtuig, speed} = objects
  const group = useRef()
  const plane = useRef()
  const boot = useRef()
  const { nodes, materials } = useGLTF('../../../planet3.glb')

  useFrame(() => {
    if (playing) {
      group.current.rotation.y += parseFloat(speed)
    }

    if (vliegtuig) {
      plane.current.rotation.z += .01
    }
  })
  return (
    <group ref={group} dispose={null}>
      {/* boten */}
      { boten &&
        <>
          <group ref={boot} position={[-0.29, 0.64, 0.69]} rotation={[0.32, 0.94, 0.47]} scale={[-0.32, -0.08, -0.08]}>
            <mesh geometry={nodes.Plane002.geometry} material={materials.boat} />
            <mesh geometry={nodes.Plane002_1.geometry} material={materials.muren} />
          </group>
          <group ref={boot} position={[0.73, -0.66, 0.06]} rotation={[0.39, -0.36, -2.25]} scale={[-0.32, -0.08, -0.08]}>
            <mesh geometry={nodes.Plane065.geometry} material={materials.boat} />
            <mesh geometry={nodes.Plane065_1.geometry} material={materials.muren} />
          </group>
          <group ref={boot} position={[-0.45, 0.09, -0.87]} rotation={[-1.96, 0.74, 0.6]} scale={[-0.32, -0.08, -0.08]}>
            <mesh geometry={nodes.Plane066.geometry} material={materials.boat} />
            <mesh geometry={nodes.Plane066_1.geometry} material={materials.muren} />
          </group>
        </>
      }

      {/* huizen */}
      { huizen &&
        <>
          <mesh geometry={nodes.Plane001.geometry} material={materials.muren} />
          <mesh geometry={nodes.Plane001_1.geometry} material={materials.dak} />
        </>
      }

      {/* bomen */}
      { bomen &&
        <group position={[-0.7, 0.08, 0.76]} rotation={[1.26, 0.2, 0.8]} scale={0.62}>
          <mesh geometry={nodes.Plane004.geometry} material={materials.wood} />
          <mesh geometry={nodes.Plane004_1.geometry} material={materials.leafs} />
        </group>
      }

      <mesh geometry={nodes.Icosphere.geometry} material={materials.water} />
      <mesh geometry={nodes.Icosphere_1.geometry} material={materials.land} />

      {/* viegtuig */}
      {vliegtuig &&
        <group ref={plane} rotation={[-2.99, -0.99, -2.87]} scale={[-0.33, -0.06, -0.06]}>
          <mesh geometry={nodes.Plane003.geometry} material={materials.muren} />
          <mesh geometry={nodes.Plane003_1.geometry} material={materials.dak} />
          <mesh geometry={nodes.Plane003_2.geometry} material={materials.glass} />
        </group>
      }
    </group>
  )
}

useGLTF.preload('../../../planet3.glb')
